# Generated by Django 3.1.3 on 2021-03-29 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mommy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reciever',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to=settings.AUTH_USER_MODEL),
        ),
    ]
